[[ClangBootstrap]]
arch = "x86_64"
git-tree-sha1 = "70ab6ddbfb28b0a6ffc577975ce037801352b8df"
libc = "glibc"
os = "linux"
target = "any"

    [[ClangBootstrap.download]]
    sha256 = "aab3e469d41a2e5b025cf273c4d7d8386b407e0cef5ff086828e379dbf4f2955"
    url = "https://github.com/staticfloat/ClangBootstrap_jll.jl/releases/download/v17.0.0-ClangBootstrap/ClangBootstrap-v17.0.0-x86_64-linux-gnu-target+any.tar.gz"
[[ClangBootstrap]]
arch = "aarch64"
git-tree-sha1 = "bd06ce757f0b4f2ad8beb82b9b2886913fa93743"
libc = "glibc"
os = "linux"
target = "any"

    [[ClangBootstrap.download]]
    sha256 = "d75e34e6fdbcd2b83abf1981c027868aa63a22b53da5396d518c44ece4d49a9d"
    url = "https://github.com/staticfloat/ClangBootstrap_jll.jl/releases/download/v17.0.0-ClangBootstrap/ClangBootstrap-v17.0.0-aarch64-linux-gnu-target+any.tar.gz"

[[ClangBootstrap-build_log]]
arch = "x86_64"
git-tree-sha1 = "3ed0492a44bdf537f04933456eacecd046b92b2a"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[ClangBootstrap-build_log.download]]
    sha256 = "70d87f87231513c9aa09dfbf2a20eea40ea0df13ff8ba19ec31bba0517b6e9a3"
    url = "https://github.com/staticfloat/ClangBootstrap_jll.jl/releases/download/v17.0.0-ClangBootstrap/ClangBootstrap-build_log-v17.0.0-x86_64-linux-gnu-target+any.tar.gz"
[[ClangBootstrap-build_log]]
arch = "aarch64"
git-tree-sha1 = "8e4b5863a66070abecc58344a419bdd960a0e15f"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[ClangBootstrap-build_log.download]]
    sha256 = "c3557d453f4bca13cc29113b176bb1b59406604c5d8f5186dc4b712aa2f8d430"
    url = "https://github.com/staticfloat/ClangBootstrap_jll.jl/releases/download/v17.0.0-ClangBootstrap/ClangBootstrap-build_log-v17.0.0-aarch64-linux-gnu-target+any.tar.gz"

[[ClangBootstrap-extract_log]]
arch = "x86_64"
git-tree-sha1 = "50bd5aeab2e661e1770d965610695d610e2797c5"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[ClangBootstrap-extract_log.download]]
    sha256 = "8cb5da1b3b458b5811604f0bcf61448c01b6a0c3ae50f10ff388c426980924f1"
    url = "https://github.com/staticfloat/ClangBootstrap_jll.jl/releases/download/v17.0.0-ClangBootstrap/ClangBootstrap-extract_log-v17.0.0-x86_64-linux-gnu-target+any.tar.gz"
[[ClangBootstrap-extract_log]]
arch = "aarch64"
git-tree-sha1 = "8fa5df65fcb6d5f054a07df8f64cf3f6859160b2"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[ClangBootstrap-extract_log.download]]
    sha256 = "98258b8efc92d81c4d562d17ae3b1e74b80c0e7f660cca024114c000d9231a09"
    url = "https://github.com/staticfloat/ClangBootstrap_jll.jl/releases/download/v17.0.0-ClangBootstrap/ClangBootstrap-extract_log-v17.0.0-aarch64-linux-gnu-target+any.tar.gz"
